name: Deploy helm chart

on:
  workflow_call:
    inputs:
      image_tag:
        type: string
        required: true
        description: Image tag for values file. Expect image.tag parameter.
      k8s_environment:
        type: string
        required: true
        description: Kubernetes environment. One of supported in the organization.
      helm_release_name:
        type: string
        required: true
        description: Helm release name.
      helm_chart_path:
        type: string
        required: true
        description: Helm chart path. Supports links for published charts.
      k8s_namespace:
        type: string
        required: true
        description: Kubernetes namespace for helm chart installation.
      helm_timeout:
        type: string
        required: false
        description: Helm install timeout.
        default: "2m"

jobs:
  deploy:
    permissions:
      id-token: write
      contents: write
      pull-requests: write
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: "actions/checkout@v2"

      - name: Setup helm
        uses: "azure/setup-helm@v1"

      - name: Setup yq
        uses: "chrisdickinson/setup-yq@latest"

      - name: Deploy with helm
        run: |
          helm upgrade '${{ inputs.helm_release_name }}' '${{ inputs.helm_chart_path }}' --atomic --install --wait --timeout='${{ inputs.helm_timeout }}' --namespace='${{ inputs.k8s_namespace }}' --values='${{ inputs.helm_chart_path }}/values.yaml' --values='${{ inputs.helm_chart_path }}/values/${{ inputs.k8s_environment }}.yaml' --set image.tag='${{ inputs.image_tag }}'

      - name: Update version in values
        env:
          NEW_IMAGE_TAG: ${{ inputs.image_tag }}
        run: |
          yq w -i 'helm/values/${{ inputs.k8s_environment }}.yaml' image.tag ${NEW_IMAGE_TAG}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          title: "chore(noticket): bump image version"
