name: ci / pr

on:

  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:

  # Validate PR conventions.
  conventions:
    uses: firebolt-analytics/gha-workflows/.github/workflows/conventional_pr.yaml@main

  semantic_release:
    uses: firebolt-analytics/gha-workflows/.github/workflows/semantic_release.yaml@no_issue_versionning
    with:
      template: simple
