name: ci / push

on:
  push:
    branches:
      - main

jobs:

  # Generate new release
  semantic_release:
    uses: firebolt-analytics/gha-workflows/.github/workflows/semantic_release.yaml@main
    with:
      template: simple
