name: semantic-release

on:
  workflow_call:
    inputs:
      template:
        required: true
        type: string
    outputs:
      new_release_published:
        value: ${{ jobs.generate.outputs.new_release_published }}
      new_release_version:
        value: ${{ jobs.generate.outputs.new_release_version }}
      new_release_channel:
        value: ${{ jobs.generate.outputs.new_release_channel }}
      new_release_notes:
        value: ${{ jobs.generate.outputs.new_release_notes }}

jobs:

  generate:
    runs-on: ubuntu-latest
    if:
      contains('
      refs/heads/main
      refs/heads/master
      refs/heads/staging
      refs/heads/release
      ', github.ref)
    outputs:
      new_release_published: ${{ steps.semantic_release.outputs.new_release_published }}
      new_release_version: ${{ steps.semantic_release.outputs.new_release_version }}
      new_release_channel: ${{ steps.semantic_release.outputs.new_release_channel }}
      new_release_notes: ${{ steps.semantic_release.outputs.new_release_notes }}
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure registry
        run: |
          npm config set @firebolt-analytics:registry https://npm.pkg.github.com
          npm config set //npm.pkg.github.com/:_authToken ${{ secrets.GITHUB_TOKEN }}

      - name: Semantic release
        id: semantic_release
        uses: cycjimmy/semantic-release-action@v2
        with:
          semantic_version: 18
          extends: |
            @firebolt-analytics/semantic-release-config-${{ inputs.template }}
          extra_plugins: |
            conventional-changelog-conventionalcommits@4
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish:
    needs:
      - generate
    runs-on: ubuntu-latest
    if: ${{ needs.generate.outputs.new_release_published }}
    steps:

      - name: Publish GitHub release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ needs.generate.outputs.new_release_version }}
          body: ${{ needs.generate.outputs.new_release_notes }}
